Cmd = {
    eGuestLoginReq        = 1,
    eGuestLoginRes        = 2,
    eReloginRes           = 3,
    eUserLostConn         = 4,
    eEditProfileReq       = 5,
    eEditProfileRes       = 6,
    eGuestUpgradeReq      = 7,
    eGuestUpgradeRes      = 8,
    eUserLoginReq         = 9,
    eUserLoginRes         = 10,
    eLogoutReq            = 11,
    eLogoutRes            = 12,
    eGetUGameInfoReq      = 13,
    eGetUGameInfoRes      = 14,
    eRecvLoginBonusReq    = 15,
    eRecvLoginBonusRes    = 16,
    eGetWorldRankUchipReq = 17,
    eGetWorldRankUchipRes = 18,
    eGetSysMsgReq         = 19,
    eGetSysMsgRes         = 20,
    eLogicLoginReq        = 21,
    eLogicLoginRes        = 22,
    eEnterZoneReq         = 23,
    eEnterZoneRes         = 24,
    eEnterMatch           = 25,
    eOnOtherEnteredMatch  = 26,
    eQuitMatchReq         = 27,
    eQuitMatchRes         = 28,
    eOnOtherQuittedMatch  = 29,
    eGameStart            = 30,
    eLogicFrame           = 31,
}

return Cmd
