local cmd_name_map = {
    "GuestLoginReq",
    "GuestLoginRes",
    "ReloginRes",
    "UserLostConn",
    "EditProfileReq",
    "EditProfileRes",
    "GuestUpgradeReq",
    "GuestUpgradeRes",
    "UserLoginReq",
    "UserLoginRes",
    "LogoutReq",
    "LogoutRes",
    "GetUGameInfoReq",
    "GetUGameInfoRes",
    "RecvLoginBonusReq",
    "RecvLoginBonusRes",
    "GetWorldRankUchipReq",
    "GetWorldRankUchipRes",
    "GetSysMsgReq",
    "GetSysMsgRes",
    "LogicLoginReq",
    "LogicLoginRes",
}

return cmd_name_map;
